### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by xabier** [decidim/decidim-module-blogs#1]
This functionality will consist of developing a new Component (decidim-blog) for Participatory Processes, decidim-blog, that will allow a Participatory Process Administrator to add Posts to a Process, which will be shown chronologically (most recent first). Each Post will initially have the Title and Description fields, and these fields may be internationalised (translated) into different languages, as the platform currently allows for other fields. For example, if Spanish and Catalan are enabled, it should be possible to add both the title and the description for the form. Comments on blog posts can be activated.

**Comment by isaacmg410** [comment]
@decidim/lot-core I've this issue almost ready. It needs some improvements and tests spoken today in the meeting with @decidim/product. Do you want a PR or maybe wait until I have the tests?

**Comment by mrcasals** [comment]
@isaacmg410 sorry for the late reply (been on holidays). We prefer having early PRs, so diffs can be reviewed more periodically and early feedback can save us all some hours of headaches 😄

**Comment by isaacmg410** [comment]
@arnaumonty, the user who creates the post, is automatically assigned to the current_user (the user who is writing the post) or do you want a selector for that users of the process?

**Comment by isaacmg410** [comment]
@decidim/lot-core What is the best way to sort the posts according to how many comments they have? 
Would it be correct to use counter_cache and a column in the table of posts to keep the number of comments?

**Comment by xabier** [comment]
@isaacmg410 this feature is urgent, what is missing to add this to the next release? @decidim/lot-px cannot be a stopper here. We release as is and then improve design unless design is functionally critical

**Comment by carolromero** [comment]
here is the design PR: https://github.com/decidim/decidim/pull/2430

**Comment by isaacmg410** [comment]
Until yesterday the PR of design was not accepted. This week I will apply the design. When will the next release be?

**Comment by mrcasals** [comment]
Since this is in a different repo, you are not bound to decidim's versions. Yesterday we released version 0.9, but you can release your own version whenever you want to.

**Comment by isaacmg410** [comment]
@decidim/lot-px Where can I find the blog icon for the participatory process menu? related to [#174](https://github.com/decidim/design/issues/174)

**Comment by Crashillo** [comment]
I provide you two icons: [icons.zip](https://github.com/decidim/decidim-module-blogs/files/1698356/icons.zip)
1. Blog itself
2. New proposal icon (due to its likeness)
Both should be convert into symbols and append (or replace) them in `assets/images/icons.svg`

**Comment by isaacmg410** [comment]
Since this is in a different repo, I don't think I should be the person who replace the proposal icon. @decidim/product Who should do it, this?
@Crashillo can you send me the blog icon as a symbol, please?

**Comment by Crashillo** [comment]
Are you working in some other branch? Because blog branch was already merged, now I may give you the snippets, and you add it, or the icons file updated itself. As you wish.

**Comment by isaacmg410** [comment]
I'm working in other repo [decidim-module-blogs](https://github.com/decidim/decidim-module-blogs). Can you send me the blog icon as a symbol, and I will add it.  I think that change the proposal icon, does not have to do it in this task.

**Comment by Crashillo** [comment]
I think it's related, according to [this](https://github.com/decidim/design/issues/174#issuecomment-351034690), I guess it was approved by @decidim/product. But in any case, I give you both:

Blog:
`<symbol id="icon-blog" viewBox="0 0 36 36" ><title>blog</title><g stroke="#7E7C7C" stroke-width="2" fill="none" fill-rule="evenodd" transform="translate(1 1)" stroke-linecap="round" stroke-linejoin="round"><path d="M34 17c0 9.389-7.61 17-17 17-9.389 0-17-7.611-17-17S7.611 0 17 0c9.39 0 17 7.611 17 17zM10 11h14M10 15h10M10 19h14M10 23h10"/></g></symbol>`

Proposals:
`<symbol id="icon-proposals" viewBox="0 0 36 36" ><title>proposals-new</title><g stroke="#777677" stroke-width="2" fill="none" fill-rule="evenodd" transform="translate(1 1)" stroke-linecap="round" stroke-linejoin="round"><path d="M34.016 17.008c0 9.393-7.614 17.008-17.008 17.008C7.615 34.016 0 26.4 0 17.008 0 7.615 7.615 0 17.008 0c9.394 0 17.008 7.615 17.008 17.008z"/><path d="M18.916 7.167h-9.66v19.682H24.76v-14.18h-5.843zM18.916 7.167l5.843 5.503M13.132 19.154h7.91M13.132 22.35h7.91M13.132 19.153h7.91M13.132 15.956h3.954"/></g></symbol>`

Pay attention to the `id`, you might want to rename them accordingly.

**Comment by arnaumonty** [comment]
@isaacmg410 Great job guys! Is it ready to merge?
When the component be finished we should start to integrate to the main repo as a new engine.
cc @josepjaume

**Comment by isaacmg410** [comment]
For me, is ready to merge. If someone of @decidim/lot-core could take a view to #5 and check what happens with circleci, would be fantastic

**Comment by mrcasals** [comment]
@isaacmg410 you can copy the CircleCI integration from `decidim-initiatives`.
