### ISSUE TITLE
Integrate CircleCI, Codecov and CodeClimate

### ISSUE THREAD

**Issue by mrcasals** [decidim/decidim-module-blogs#3]
Adapt the config from the main repo for those services. Ping someone from @decidim/lot-core if you need permissions on the repo to add them.

**Comment by isaacmg410** [comment]
@mrcasals Is there a document explaining how to integrate these services?

**Comment by mrcasals** [comment]
@isaacmg410 I don't think so, no, but should be pretty straight-forward. Copy the configs from the main repo, adapt them for this repo, enable the repo in each service and should be good to go.

Initiatives has a customized CircleCI config, if you want to copy that one.
