### ISSUE TITLE
Issue editing and deleting a specific post

### ISSUE THREAD

**Issue by Hilfe** [decidim/decidim-module-blogs#6]
# This is a Bug Report 

#### :tophat: Description

* What went wrong?
  When you try to edit a old post in the admin view, you can edit only the last one. Same with delete option. 

* What did you expect should have happened?
   Edit and delete the same post that you choose by clicking on the corresponding icon

* What was the config you used? 
   decidim 0.9.2 + decidim-module-blog 0.10.0-pre

* What stacktrace or error message from your provider did you see?
   Any

**Comment by mrcasals** [comment]
This issue was moved to decidim/decidim#3327
